sudo: required
language: generic
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - ros-dps-interest@amazon.com
services:
    - docker
script:
    - ./travis_build.sh
